---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Assign VLAN to eth0 on host2
    ovirt_host_networks:
      auth: "{{ ovirt_auth }}"
      name: host2
      interface: eth0
      networks:
        - name: VLAN100_Network
          boot_protocol: none
      save: true
      check: true
