---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Unassign VLAN from eth0 on host2
    ovirt_host_networks:
      state: absent
      auth: "{{ ovirt_auth }}"
      name: host2
      interface: eth0
      networks:
        - name: VLAN100_Network
      save: true
      check: true
