---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Create datacenter
    ovirt_datacenters:
      auth: "{{ ovirt_auth }}"
      name: mydatacenter2
      description: mydatacenter2
      local: True
      compatibility_version: 4.0
      quota_mode: disabled
