---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Create network
    ovirt_networks:
      auth: "{{ ovirt_auth }}"
      datacenter: test_dc
      name: test_network
      vlan_tag: 4
      vm_network: yes
      clusters:
        - name: test_cluster
          assigned: yes
          required: yes
          display: no
          migration: yes
          gluster: yes
