---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: List
    ovirt_networks_facts:
      auth: "{{ ovirt_auth }}"
      pattern: name=mynetwork

  - name: Print
    debug:
      var: ovirt_networks
