---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Delete foreman
    ovirt_external_providers:
      auth: "{{ ovirt_auth }}"
      state: absent
      type: foreman
      name: sat
