---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Create cluster
    ovirt_clusters:
      auth: "{{ ovirt_auth }}"
      name: test_cluster
      datacenter: test_dc
      cpu_type: Intel Nehalem Family
      migration_policy: suspend_workload
