---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Add quota
    ovirt_quotas:
      auth: "{{ ovirt_auth }}"
      name: quota1
      datacenter: mydatacenter
      storage_grace: 40
      storage_threshold: 60
      storages:
          - name: data2
            size: 100
      clusters:
          - memory: 30
            cpu: 15
