---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: List quota
    ovirt_quota_facts:
      auth: "{{ ovirt_auth }}"
      name: quota1
      datacenter: mydatacenter
      clusters:
        - memory: 40GiB
          cpu: 15
