---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Removequota
    ovirt_quotas:
      state: absent
      auth: "{{ ovirt_auth }}"
      name: quota1
      datacenter: mydatacenter
