---
- name: Remove permission to group
  ovirt_permissions:
      state: absent
      auth: "{{ ovirt_auth }}"
      authz_name: "{{ aaa_authz_name }}"
      group_name: "{{ group }}"
      object_type: vm
      object_name: "{{ vm1 }}"

- name: Remove permission to user
  ovirt_permissions:
      state: absent
      auth: "{{ ovirt_auth }}"
      authz_name: "{{ aaa_authz_name }}"
      user_name: "{{ user }}"
      object_type: vm
      object_name: "{{ vm1 }}"

- name: Remove user
  ovirt_users:
    state: absent
    auth: "{{ ovirt_auth }}"
    name: "{{ user }}"
    authz_name: "{{ aaa_authz_name }}"

- name: Remove group
  ovirt_groups:
    state: absent
    auth: "{{ ovirt_auth }}"
    name: "{{ group }}"
    authz_name: "{{ aaa_authz_name }}"

- name: Remove AAA files
  file:
    state: absent
    path: /etc/ovirt-engine/{{ item }}.properties
  become: yes
  with_items:
    - extensions.d/{{ aaa_authz_name }}
    - extensions.d/{{ aaa_profile_name }}-authn
    - aaa/{{ aaa_profile_name }}

- name: Remove answer file
  file:
    state: absent
    path: /tmp/aaa_answer_file.conf

