---
## Destroy sanity objects
- name: Remove scratch VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: absent
    name: "{{ item }}"
  with_items:
    - "{{ vm0 }}"
    - "{{ vm1 }}"

- name: Delete VM pool
  ovirt_vmpools:
    auth: "{{ ovirt_auth }}"
    state: absent
    name: "{{ vmpool }}"

- name: Remove template
  ovirt_templates:
    auth: "{{ ovirt_auth }}"
    state: absent
    name: "{{ template }}"
