---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: List
    ovirt_nics_facts:
      auth: "{{ ovirt_auth }}"
      vm: myvm
      name: m*

  - name: Debug
    debug:
      var: ovirt_nics
