---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Create disk and attach it to VM
    ovirt_disks:
      auth: "{{ ovirt_auth }}"
      name: mydisk
      size: 1GiB
      storage_domain: data
      vm_id: 
