---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Create disk and attach it to VM
    ovirt_disks:
      auth: "{{ ovirt_auth }}"
      id: 3e7aa474-38bc-4cd8-af84-50ca9373ba08
      storage_domain: data2
