---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Upload disk
    ovirt_disks:
      auth: "{{ ovirt_auth }}"
      name: test7
      size: 1GiB
      format: cow
      image_path: /home/omachace/libvirt/test3.qcow2
      storage_domain: data
