---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Add SD
    ovirt_storage_domains:
      auth: "{{ ovirt_auth }}"
      name: data
      description: test
      host: host1
      data_center: test_dc
      nfs:
        address: 192.168.200.13
        path: /exports/nfs_clean/share1
        version: v3
        timeout: 100
        retrans: 10
