---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Create MAC pool
    ovirt_mac_pools:
      auth: "{{ ovirt_auth }}"
      name: test_pool
      description: Test pool
      allow_duplicates: false
      ranges:
        - 00:1a:4a:16:01:51,00:1a:4a:16:01:61
        - 00:1a:4a:16:03:51,00:1a:4a:16:03:61
        - 00:1a:4a:16:04:51,00:1a:4a:16:04:61
