---
- name: Start haveged
  service:
    name: haveged
    state: started
  become: yes

- name: Copy answerfile
  template:
    src: answerfile
    dest: /tmp/answerfile.conf
    mode: 0644

- name: Add hostname to hosts file
  lineinfile:
    line: "127.0.0.1 {{ ovirt_engine_hostname }} {{ ovirt_engine_hostname }}"
    dest: /etc/hosts
  become: yes

- name: check if ovirt-engine running (health page)
  uri:
    url: "http://{{ovirt_engine_hostname}}/ovirt-engine/services/health"
    status_code: 200
  register: ovirt_engine_status
  retries: 2
  delay: 5
  until: ovirt_engine_status|success
  ignore_errors: True

- name: Setup oVirt engine
  shell: 'engine-setup --config-append=/tmp/answerfile.conf'
  become: yes
  when: ovirt_engine_status|failed

- name: Check health status of oVirt engine
  uri:
    url: "http://{{ovirt_engine_hostname}}/ovirt-engine/services/health"
    status_code: 200
  register: health_page
  retries: 12
  delay: 10
  until: health_page|success

- name: Remove answer file
  file:
    path: '/tmp/answerfile.txt'
    state: 'absent'
